### ISSUE TITLE
SSR Doesnt Work

### ISSUE THREAD

**Issue by yaronovsky** [wpengine/headless-framework#344] opened 2021-07-13 20:18 UTC
There is some kind of an issue with ssr
if you view the source of the page there is no html there
![Screen Shot 2021-07-13 at 23 16 16](https://user-images.githubusercontent.com/20338844/125518880-f2a2ff33-1fc7-4278-ab16-c3444267222f.png)
I've checked the next js official getting started, there is no problem there.
I've tried various build methods via next cli, same result.
Please fix this asap, i need the headless framework for a large project

**Comment by wjohnsto** [comment] 2021-07-13 20:27
Are you using `@wpengine/headless` or `@faustjs`?

**Comment by yaronovsky** [comment] 2021-07-14 03:35
![190F0C4D-955B-473C-98D0-F03F904116FE_4_5005_c](https://user-images.githubusercontent.com/20338844/125557029-a9e979a1-6f02-4512-bdb5-a0630757f631.jpeg)

**Comment by yaronovsky** [comment] 2021-07-14 04:32
By the way i am using local wp with the atlas plugin to start the project

**Comment by yaronovsky** [comment] 2021-07-14 09:01
The issue has to do with the NextTemplateLoader, If i replace it with html or other components everything is fine.
Thanks in advance

**Comment by wjohnsto** [comment] 2021-07-14 20:46
We have experience a bunch of issues with the way the `wp-templates` works with Next's `getStaticProps` and `getServerSideProps`, and in general we recommend not using it. We also have a new version of the framework being released as `@faustjs` that will soon replace `@wpengine/headless`. It shouldn't be too difficult to migrate to `@faustjs`, but if you are too far into it that you are unable to migrate I can try to help you through the issue.

To really get a sense of where the problem is occurring it would be good to see the code for `getStaticProps` or `getServerSideProps` in BOTH your Next page as well as the template component if it is implemented there.

**Comment by yaronovsky** [comment] 2021-07-15 00:29
Actually i havent gone to deep yet, can wait for faust js.

**Comment by wjohnsto** [comment] 2021-07-15 01:34
We have the getting-started up for that framework here: https://github.com/wpengine/headless-framework/tree/canary/examples/next/getting-started

There are still some quirks, but we're working through them.

**Closed** 2021-07-16 19:30 UTC
